// LinkFYR documentation content (discord-botlists docs architecture).
// Generated from the source markdown during the docs migration; this file
// is now the single source of truth, like the other PotenFYR docs sites.

export type DocCategory = "Start here" | "Security" | "Design and background";

export type DocBlock =
  | { type: "text"; content: string }
  | { type: "h3"; content: string }
  | { type: "code"; lang: string; content: string }
  | { type: "table"; headers: string[]; rows: string[][] }
  | { type: "note"; tone: "info" | "warn" | "tip"; content: string }
  | { type: "list"; items: string[] };

export interface DocSection {
  slug: string;
  title: string;
  blurb: string;
  category: DocCategory;
  blocks: DocBlock[];
}

export const DOC_CATEGORIES: DocCategory[] = ["Start here", "Security", "Design and background"];

export const DOC_SECTIONS: DocSection[] = [
  {
    slug: "adr/0001-application-shell",
    title: "ADR-0001: Application shell",
    blurb: "Why Tauri 2, and the replaceable-shell rule.",
    category: "Design and background",
    blocks: [
      { type: "text", content: "# ADR-0001: Application Shell â€” Tauri 2 over Alternatives" },
      { type: "text", content: "Status: Accepted (2026-09-30) Deciders: LinkFYR architecture team" },
      { type: "h3", content: "Context" },
      { type: "text", content: "LinkFYR needs one application shell that reaches every target platform: Windows x64/ARM64, macOS Apple Silicon/Intel, Linux x64/ARM64, Android ARM64/x86_64, iOS/iPadOS ARM64 â€” plus headless targets (servers, SBCs, routers, containers) where **no GUI shell exists at all**. The networking engine is Rust. The UI must support premium real-time charts, animation, dark/light theming, accessibility, and a signed auto-updater." },
      { type: "h3", content: "Options evaluated (checked 2026-09-30)" },
      { type: "table", headers: ["Option", "Version", "All-OS reach", "UI quality ceiling", "Accessibility", "Updater", "Verdict"], rows: [["**Tauri 2**", "2.12.0", "Desktop stable; iOS/Android stable channel", "Full web platform (charts, animation, a11y)", "Web a11y tree", "First-class plugin (`tauri-plugin-updater`, signed manifests)", "**Chosen**"], ["Electron", "44.5.1", "Desktop + limited mobile story", "Full web platform", "Web a11y", "Mature", "~10Ã, memory baseline; bundles Chromium; contradicts low-footprint goal"], ["Dioxus", "0.7.10", "Desktop + mobile (native renderer)", "Improving but 0.x; chart/animation ecosystem immature", "Weak", "Custom", "Re-evaluate yearly; shares Rust model"], ["iced", "0.14.0", "Desktop; mobile/experimental", "Immediate-mode; heavy custom charting work", "Weak", "Custom", "Not viable for premium a11y UI"], ["egui", "0.36.2", "Desktop; mobile weak", "Power-tool aesthetic only", "Weak", "Custom", "Wrong product fit"], ["Slint", "1.18.1", "Desktop + mobile + embedded", "Good", "Moderate", "Custom", "**GPL/commercial dual license** â€” GPL terms are incompatible with our distribution model, and the commercial license is a fee we will not pay (project is fully free)"], ["Flutter", "3.x stable", "Mobile strong, desktop weaker", "High", "Good", "Mature (mobile), weaker desktop", "Second language (Dart) alongside Rust core; desktop windowing/IPC maturity below web"], ["Qt/QML (CXX-Qt)", "6.x", "Desktop + mobile", "High", "Good", "Mature", "Licensing cost + C++ toolchain complexity"], [".NET MAUI / Avalonia", "11.x", "Desktop + mobile", "Good", "Good", "Moderate", "Forces C# runtime; networking engine would still be Rust â†’ two runtimes"]] },
      { type: "h3", content: "Decision" },
      { type: "text", content: "**Tauri 2 is the application shell.** One TypeScript/React frontend, one Rust core, system WebView per platform (WebView2 / WKWebView / WebKitGTK)." },
      { type: "h3", content: "Anti-lock-in mitigation (binding architectural rule)" },
      { type: "text", content: "The shell is a *replaceable client*. All product capability lives in Rust crates behind the stable `linkfyr-ipc` API surface:" },
      { type: "code", lang: "text", content: "UI (Tauri 2) â”€â”\nCLI â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â†’ linkfyr-ipc (stable, versioned, typed) â†’ linkfyr-core â†’ engine\nlinkfyrd â”€â”€â”€â”€â”€â”˜         â”‚\nremote/mobile clients â”€â”€â”˜ (authenticated transport, later phase)" },
      { type: "text", content: "Rules that follow:" },
      { type: "list", items: ["**No business logic in the frontend.** The frontend renders state and issues commands; everything else is Rust.", "**No Tauri types outside `apps/desktop`.** Crates never depend on `tauri`; only the desktop app wires Tauri commands to `linkfyr-ipc`.", "**Headless parity.** Every GUI action must be expressible via `linkfyrd` + `linkfyr` CLI. CI enforces feature parity for core APIs.", "If Tauri mobile ever proves insufficient, a native mobile shell can be built against the same IPC API without touching the engine."] },
      { type: "h3", content: "Consequences" },
      { type: "list", items: ["+ Smallest memory footprint of the viable options; signed updates built in.", "+ Single UI codebase for 6 GUI platforms; headless targets skip the shell entirely.", "âˆ’ WebView variance (WebKitGTK on Linux) â€” mitigated by a browser-support matrix in CI and avoiding bleeding-edge CSS in core flows.", "âˆ’ Tauri mobile is younger than desktop â€” acceptable: mobile phases are Phase 8; the IPC boundary keeps the option to switch shells open."] },
    ],
  },
  {
    slug: "architecture",
    title: "Architecture",
    blurb: "Process topology, crate map, data flow, and performance budgets.",
    category: "Start here",
    blocks: [
      { type: "text", content: "Status: living document · Last updated: 2026-09-30" },
      { type: "h3", content: "1. Product thesis" },
      { type: "text", content: "LinkFYR is *the operating system for your Internet connections*: a network control layer that unifies what today requires Speedify + NetLimiter + GlassWire + Little Snitch/Portmaster + a VPN client + diagnostics tools, integrated, transparent, cross-platform, and privacy-first." },
      { type: "text", content: "The competitive moat is **integration**: telemetry feeds automation, automation feeds routing, routing respects reservations, reservations respect link health, health feeds bonding, bonding integrates with VPN and per-app policy, and history explains every automatic decision." },
      { type: "h3", content: "2. Process & trust topology" },
      { type: "code", lang: "text", content: "┌──────────────────────────────────────────────────────────────┐\n│ Unprivileged                                                  │\n│  linkfyr-gui (Tauri 2)   linkfyr (CLI)   linkfyr-tray         │\n│        │                      │                               │\n│        └────────┬─────────────┘                                │\n│                 ▼                                              │\n│  linkfyr-ipc  (typed, versioned API, no Tauri types here)    │\n└─────────────────┬────────────────────────────────────────────┘\n                  │ authenticated local IPC\n                  │  • Windows: named pipe, ACL-restricted\n                  │  • macOS:   unix domain socket (per-user)\n                  │  • Linux:   unix domain socket (per-user)\n                  │  • auth:    mutating-session token + origin check\n┌─────────────────▼────────────────────────────────────────────┐\n│ linkfyrd, privileged networking service (runs as SYSTEM/root)│\n│  linkfyr-core      orchestration, config, profiles, policy    │\n│  linkfyr-network   platform abstraction (see §4)              │\n│  linkfyr-rules     Flow Rules engine + automations            │\n│  linkfyr-telemetry ring buffer, storage, downsampling         │\n│  linkfyr-protocol  Fusion multipath tunnel protocol           │\n│  linkfyr-edge      Edge node (self-host or hosted)            │\n└──────────────────────────────────────────────────────────────┘" },
      { type: "text", content: "Trust rules:" },
      { type: "list", items: ["The GUI/CLI **never** run elevated. They are clients of `linkfyrd`.", "`linkfyrd` exposes a deliberately small IPC surface; every message is schema-checked; unauthenticated or unversioned frames are dropped.", "Security-sensitive features define explicit **fail-open / fail-closed** policy (see https://linkfyr.docs.potenfyr.in/docs/security/) that the user can see and change."] },
      { type: "h3", content: "3. Crate map (Cargo workspace)" },
      { type: "table", headers: ["Crate", "Role", "Elevated?"], rows: [["`linkfyr-core`", "Orchestrator: config store, profile state, scheduler harness, event bus, health engine", "service"], ["`linkfyr-network`", "Platform abstraction: interfaces, per-app accounting, traffic control hooks", "service"], ["`linkfyr-rules`", "Flow Rules AST, evaluation, automation triggers, Connection Composer lowering", "service"], ["`linkfyr-telemetry`", "In-memory ring buffers + on-disk time-bucketed store, downsampling, retention", "service"], ["`linkfyr-optimize`", "Optimization toolkit: DNS benchmark/apply, route scan, bufferbloat grading, speed test, MTU discovery, TCP audit, Wi-Fi analysis, route audit, repair actions, the 100+ tool registry. Pure-Rust, cross-platform, unprivileged measurement core; mutations (DNS apply) are explicit, reversible, elevation-honest", "service"], ["`linkfyr-bridge`", "Network bridge manager: tiered Hyper-V SET / NetNat / Linux / macOS L2 with injection-validated specs and elevation-honest reports", "service"], ["`linkfyr-daemon`", "`linkfyrd` background service: hosts the engine over an authenticated loopback transport (IPC envelope reuse); Windows SCM, systemd, launchd integration", "service"], ["`linkfyr-protocol`", "Fusion tunnel protocol: framing, crypto, path scheduler, FEC/redundancy", "service"], ["`linkfyr-ipc`", "The stable API: message schemas, request/response envelope, event stream", "both"], ["`linkfyr-cli`", "`linkfyr` binary: status, interfaces, apps, traffic, rules, profile, diagnose", "user"], ["`linkfyr-edge`", "`linkfyrd-edge` binary: terminates Fusion tunnels, reorders, forwards", "server"], ["`apps/desktop`", "Tauri 2 GUI (the only place Tauri types exist)", "user"]] },
      { type: "text", content: "Forward-compat placeholders (crate reserved, module stubbed, roadmap-locked): per-app platform modules inside `linkfyr-network` (`wfp`, `ne`, `nft`), `linkfyr-protocol::fec`, `linkfyr-rules::dsl`, remote-management module in `linkfyr-core`. **Nothing in early phases may make these harder to add.**" },
      { type: "h3", content: "4. Platform abstraction (linkfyr-network)" },
      { type: "text", content: "One trait surface, N implementations:" },
      { type: "code", lang: "rust", content: "pub trait InterfaceMonitor: Send {\n    fn snapshot(&self) -> Vec<Interface>;           // discovery + state\n    fn counters(&self) -> Vec<IfCounters>;          // rx/tx bytes, packets, errors\n}\n\npub trait AppTrafficMonitor: Send {                 // Phase 2\n    fn flows(&self) -> Vec<FlowRecord>;             // per-process connection table\n}\n\npub trait TrafficControl: Send {                    // Phase 3+\n    fn apply(&mut self, plan: &ControlPlan) -> Result<ApplyReport>;\n    fn clear(&mut self) -> Result<()>;              // MUST be fail-safe\n}" },
      { type: "table", headers: ["Capability", "Windows", "macOS", "Linux", "Android", "iOS"], rows: [["Interface discovery/counters", "GetIfTable2/IP Helper", "NetworkExtension/sysctl", "netlink/`/sys/class/net`", "VpnService+ConnectivityManager", "NE"], ["Per-app accounting", "WFP + ETW", "NE filter (needs approval)", "nftables owner match (`cgroup`/uid)", "VpnService", "limited by OS"], ["Per-app control", "WFP (user-mode first)", "NE content filter", "nftables + tc", "VpnService", "NE (limited)"], ["Shaping/priority", "WFP + qWAVE", "NE + dummynet-era APIs / pq", "tc qdiscs (netem/fq/cake)", "VpnService queues", "NE"], ["Bonding (Fusion)", "userspace UDP tunnel", "same", "same (TUN)", "VpnService TUN", "NE PacketTunnel"], ["eBPF observability", "—", "—", "✓ where kernel allows", "—", "—"]] },
      { type: "text", content: "User-mode first on Windows (WFP via the `windows` crate / callout-free redirects); a kernel callout driver is a **later, optional** component. No parity faking: the UI renders a capability matrix per platform." },
      { type: "h3", content: "5. Data flow (Phase 1 vertical slice, shipped now)" },
      { type: "code", lang: "text", content: "InterfaceMonitor (1 Hz)          HealthEngine\n   │ counters Δ                      │ per-interface score\n   ▼                                 ▼\nTelemetryEngine ──ring buffers──▶ SnapshotBus ──▶ IPC events ──▶ UI charts\n   │                                                    │\n   ▼                                                    ▼\nStore (SQLite, bucketed)                         CLI / linkfyrd status" },
      { type: "list", items: ["Counters are delta-based; poll-period jitter is handled by timestamp differencing, never by assuming a fixed period.", "Ring buffers feed 1 s-resolution charts; the store downsamples (1 s → 1 min → 1 h) with configurable retention (https://linkfyr.docs.potenfyr.in/docs/roadmap/ §storage).", "The scheduler (Phase 5/6) consumes the same snapshot stream. UI and engine share one truth."] },
      { type: "h3", content: "6. Fusion (Phase 6) design sketch" },
      { type: "list", items: ["Client opens N authenticated paths (initially QUIC streams / UDP flows) to one Edge endpoint; Edge reorders, dedups (path-tagged sequence numbers), applies optional redundancy/FEC, and forwards via NAT.", "Adaptive scheduler computes per-path weights from RTT/jitter/loss/ throughput/cost every ~200 ms; decisions are exposed to users verbatim (Explainability is a product feature, not a debug log).", "Redundancy modes: off / critical-only / adaptive / full.", "Selection between multipath-QUIC, MPTCP, and custom UDP transport is a **benchmark decision**, deferred to Phase 6 with recorded ADR. Protocol sketch: https://linkfyr.docs.potenfyr.in/docs/protocol/."] },
      { type: "h3", content: "7. Storage" },
      { type: "text", content: "SQLite (via a maintained Rust binding) with time-bucketed tables: `samples_1s` (recent), `samples_1m`, `samples_1h`; retention configurable; WAL mode; bounded log ring; diagnostics export is opt-in and redacted." },
      { type: "h3", content: "8. Testing strategy" },
      { type: "list", items: ["Scheduler/health/rules: deterministic unit + property tests (no real NICs).", "Network scenarios simulated via a `SimMonitor` implementing the same traits: high latency, loss, flap, asymmetric bandwidth, cap exhaustion.", "UI: component tests + Playwright-style e2e against the dev server.", "Protocol: fuzz framing/parsers, interleaved-delivery simulation tests.", "CI matrix: Windows x64, macOS arm64/x86_64, Linux x86_64 (+ arm64 cross)."] },
      { type: "h3", content: "9. Performance budgets" },
      { type: "table", headers: ["Metric", "Budget"], rows: [["linkfyrd idle CPU", "< 1% of one core"], ["telemetry sampling overhead", "< 5 MB/s allocation churn, zero unbounded growth"], ["added latency (observe-only)", "≈ 0 (pure observer)"], ["added latency (Fusion, healthy path)", "< 5 ms p50 overhead"], ["UI frame budget", "60 FPS; chart updates batched to rAF"], ["IPC chatter", "event coalescing ≥ 10 Hz for charts, on-demand for the rest"]] },
    ],
  },
  {
    slug: "competitors",
    title: "Competitor matrix",
    blurb: "Living comparison with evidence grades.",
    category: "Design and background",
    blocks: [
      { type: "text", content: "Status: living document · Updated: 2026-09-30 · Method: public docs, stores, forums, Reddit, GitHub issues. Evidence graded: ★ widespread · ☆ recurring · ˚ anecdotal." },
      { type: "h3", content: "Multi-WAN / bonding" },
      { type: "h3", content: "Speedify" },
      { type: "text", content: "Platforms: Win/macOS/Linux/Android/iOS. Pricing: freemium + subscription. Strengths: true bonding (their cloud), channel bonding UX, failover. Limitations: closed cloud required for bonding; per-app controls thin; opaque \"smart\" decisions; history/analytics weak; no firewall. Complaints: subscription cost for infrastructure users already pay for ★; can't self-host bonding ☆; telemetry/privacy concerns ☆; no per-app VPN split ☆. **Opportunities:** self-hosted Edge, explainable scheduler, per-app bonding policies, capable local multi-WAN that costs nothing." },
      { type: "h3", content: "Peplink/SpeedFusion, OpenMPTCProuter, mwan3" },
      { type: "text", content: "Router-space multi-WAN. Strengths: proven bonding/FEC (Peplink), open (OMPTC: MPTCP+VPS), free (mwan3). Limitations: hardware/router-bound, terrible UX for mortals, no per-app desktop control, no GUI history. Complaints: config complexity ★; want desktop equivalent ☆. **Opportunities:** bring router-grade multi-WAN to desktops with real UX." },
      { type: "h3", content: "Per-app control / firewall" },
      { type: "h3", content: "NetLimiter (Win)" },
      { type: "text", content: "Strengths: per-app limits, priorities, mature. Complaints: dated UI ★, pricing tiers ☆, no multi-WAN, Windows-only." },
      { type: "h3", content: "NetBalancer (Win)" },
      { type: "text", content: "Similar space; complaints: UI/perf, licensing ☆." },
      { type: "h3", content: "Little Snitch (macOS)" },
      { type: "text", content: "Gold standard ask-to-connect + rules. Complaints: price ★; no bandwidth shaping ☆; no multi-WAN ☆; silent-mode fatigue ☆." },
      { type: "h3", content: "Portmaster (macOS/Linux, Safing)" },
      { type: "text", content: "Open-core, privacy-centric, per-app DNS/blocklists. Complaints: Windows gap ☆; no bandwidth control ☆; perf overhead reports ☆; paid SPN for privacy routing." },
      { type: "h3", content: "simplewall / OpenSnitch / LuLu" },
      { type: "text", content: "Free firewalls: Windows filter frontend / Linux ask-to-connect / macOS blocker. Common gaps: no telemetry dashboards, no shaping, no multi-WAN, single-purpose. Complaints about OpenSnitch: GTK UX ☆. **Opportunities:** unified firewall + shaping + routing + visibility with modern UX; ask-to-connect that learns (rule suggestions) without fatigue." },
      { type: "h3", content: "Monitoring" },
      { type: "h3", content: "GlassWire" },
      { type: "text", content: "Strengths: beautiful graphs (the category benchmark), alerts, easy. Complaints: no per-app shaping ★; subscription backlash ☆; no Linux ★; shallow diagnostics ☆. **Opportunities:** GlassWire-grade visuals + actual control; Linux support." },
      { type: "h3", content: "VPN / identity" },
      { type: "h3", content: "Tailscale/ZeroTier" },
      { type: "text", content: "Mesh identity, great onboarding. Not traffic control/bonding. Complaints: coordination-plane reliance ☆ (self-host headscale demand ★). **Opportunity:** LinkFYR device mesh later (Phase 8) w/ self-host option." },
      { type: "h3", content: "Commercial VPN clients" },
      { type: "text", content: "Per-app split tunneling usually crude; no multi-path; no per-app DNS. **Opportunity:** per-app × per-destination × per-profile VPN matrices." },
      { type: "h3", content: "Diagnostics" },
      { type: "text", content: "ping/traceroute/MTR/WiFiAnalyzer/etc.: fragmented CLI-era UX, no integration with control. **Opportunity:** Diagnose that *acts* (creates reversible actions / rules), not just reports." },
      { type: "h3", content: "Synthesis, validated product requirements (evidence-graded)" },
      { type: "list", items: ["Per-app bandwidth control with guarantees+burst, not just caps ★", "Beautiful, fast traffic visuals ★", "Multi-WAN failover without disconnects ★; true bonding without vendor cloud lock-in ☆", "Ask-to-connect with fatigue-resistant UX ★", "Cross-platform consistency (Linux gaps everywhere) ★", "Explainable automation (\"why did it do that?\") ☆", "Self-hosting for infrastructure features ☆", "Free core that isn't crippled ☆", "Per-app VPN split by domain AND app ☆", "Modern DNS controls (DoH/DoT, blocklists) built-in ☆"] },
    ],
  },
  {
    slug: "daemon",
    title: "linkfyrd service",
    blurb: "Install the background service on Windows, Linux, and macOS.",
    category: "Start here",
    blocks: [
      { type: "text", content: "`linkfyrd` keeps the engine, optimization jobs, and bridges running while the desktop app is closed (exam-safe operation: close the GUI, the network configuration you set up stays up)." },
      { type: "h3", content: "Windows (service via SCM)" },
      { type: "text", content: "The binary speaks the Windows service protocol when started with `--service`:" },
      { type: "code", lang: "text", content: "# elevated\nsc.exe create linkfyrd binPath= \"C:\\Program Files\\LinkFYR\\linkfyrd.exe --service\" start= auto\nsc.exe description linkfyrd \"LinkFYR background network service\"\nsc.exe start linkfyrd" },
      { type: "text", content: "Remove with `sc.exe delete linkfyrd`." },
      { type: "h3", content: "Linux (systemd)" },
      { type: "code", lang: "bash", content: "sudo cp deploy/systemd/linkfyr.service /etc/systemd/system/\nsudo systemctl daemon-reload\nsudo systemctl enable --now linkfyr" },
      { type: "h3", content: "macOS (launchd)" },
      { type: "code", lang: "bash", content: "sudo cp deploy/launchd/com.linkfyr.daemon.plist /Library/LaunchDaemons/\nsudo launchctl load /Library/LaunchDaemons/com.linkfyr.daemon.plist" },
      { type: "h3", content: "Transport and auth (v1)" },
      { type: "text", content: "Loopback TCP only (default `127.0.0.1:58008`), per-user token file with `0600` permissions created on first run (`<config dir>/daemon.token`). Clients authenticate with one JSON handshake line before any request. Requests/responses are the exact `linkfyr-ipc` envelope contract, so GUI, CLI (`linkfyr daemon status`), and the daemon cannot drift." },
      { type: "text", content: "Hardening roadmap (threat model T1/T15): Windows named pipe with DACL, unix domain socket + SO_PEERCRED peer credentials, replacing the token. Elevated operations (bridge create, DNS apply) are still explicit user actions; the daemon never auto-elevates." },
    ],
  },
  {
    slug: "edge",
    title: "Edge node",
    blurb: "Self-hosted relay design.",
    category: "Design and background",
    blocks: [
      { type: "text", content: "Two deployment modes, one binary: `linkfyrd-edge`." },
      { type: "h3", content: "Self-hosted (free, first-class)" },
      { type: "code", lang: "bash", content: "docker run -d --network host \\\n  -v /etc/linkfyr-edge:/data \\\n  -e LINKFYR_EDGE_LISTEN=0.0.0.0:51820/udp \\\n  linkfyr/edge:latest\n# or native: linkfyr-edge --config /etc/linkfyr-edge/config.toml" },
      { type: "list", items: ["Enrolls devices (device key + token); terminates Fusion sessions; NAT/forwards to Internet; exports Prometheus-style metrics + accounting.", "Runs on: any VPS/cloud VM, home server, colocated box. ARM64 images.", "Hosted-Edge parity is a hard requirement (same binary, same protocol)."] },
      { type: "h3", content: "Community-hosted endpoints (optional, never gated)" },
      { type: "list", items: ["Regions/nodes appear only when real volunteer or community-run infrastructure exists; never advertised ahead of reality.", "Node selection: latency probe + capacity + user pin.", "There is no billing or entitlement layer anywhere in LinkFYR; trust for a hosted node is the operator's own trust decision (self-host by default; community nodes are opt-in and clearly labeled)."] },
      { type: "h3", content: "Operations" },
      { type: "list", items: ["Config: TOML; secrets via env/file perms, never in repo.", "Telemetry: Edge keeps only forwarding/accounting metadata + session health; no DPI, no payload logging; retention short by default.", "Upgrades: blue-green via container tags; protocol version negotiation; old clients get grace window."] },
    ],
  },
  {
    slug: "flow-rules",
    title: "Flow Rules",
    blurb: "The rules language: predicates, actions, and priorities.",
    category: "Design and background",
    blocks: [
      { type: "text", content: "Status: living spec · Engine lives in `linkfyr-rules`." },
      { type: "h3", content: "Model" },
      { type: "code", lang: "rust", content: "Rule { id, name, enabled, priority,\n  when:  Condition,          // AND of predicates; OR groups nested\n  unless: Option<Condition>, // exception\n  then: Vec<Action>,         // ordered\n}" },
      { type: "text", content: "Predicates (Phase 4 targets; engine keeps the full enum from day one so data model never migrates): app/executable/path · process user · interface (id/type/health/SSID) · destination (ip/CIDR/domain/ASN/country/port/ protocol) · traffic category · VPN active · time-of-day/day-of-week · battery/charging · network cost/metered · live metrics (latency, jitter, loss, throughput above/below threshold, sustained windows) · profile · connection state · monthly data usage thresholds." },
      { type: "text", content: "Actions: allow · block · ask · throttle(down/up) · guarantee · priority · route_to(interface(s)) · use_vpn(profile) · use_dns(resolver) · bond(mode) · redundancy(mode) · activate_profile · notify · webhook · run_diagnostics · set_mode. Every action is reversible; every execution writes an Explainability event (why, inputs snapshot, rule id, undo ref)." },
      { type: "h3", content: "Evaluation pipeline" },
      { type: "text", content: "Match phase builds a `RuleContext` from current state (app lookup, metrics snapshot, time). Rules pre-indexed by coarse keys (app, dst domain suffix) → candidate set; full eval only on candidates; first-match by priority within action classes (firewall vs routing are separate stages so a block rule can't silently cancel a route rule)." },
      { type: "h3", content: "Editors" },
      { type: "list", items: ["Beginner: card-based (\"When [app] connects to [domain] → [do this]\") with curated pickers; no free-form logic.", "Expert: full condition tree (AND/OR/NOT), metrics with windows (\"loss > 5% for 10 s\"), test-bench (simulate against last N minutes of telemetry), JSON/YAML import-export."] },
      { type: "h3", content: "Automation rules" },
      { type: "text", content: "Same engine; triggers are predicates over event streams (app launch, interface up/down, thresholds crossing with debounce, schedule, profile change). Dry-run mode logs what would happen; every automation has explain-why + disable." },
      { type: "h3", content: "Connection Composer" },
      { type: "text", content: "Visual graph (sources=interfaces/VPN/Edge, sinks=traffic classes/apps). Lowering pass compiles the graph into Flow Rules + profile, the graph is sugar, rules remain the source of truth (inspectable, exportable)." },
      { type: "h3", content: "Testing" },
      { type: "text", content: "Golden-case unit tests per predicate/action; property tests (rule set is total function over context); simulation suite replays scripted network scenarios (https://linkfyr.docs.potenfyr.in/docs/architecture/ §8) asserting expected decisions." },
    ],
  },
  {
    slug: "mobile",
    title: "Mobile companion",
    blurb: "Build the Tauri 2 app for Android and iOS.",
    category: "Start here",
    blocks: [
      { type: "text", content: "The mobile companion is a Tauri 2 app in `apps/mobile`, in this repo. It shares the entire desktop UI source (`apps/mobile/src/main.tsx` imports the desktop `App`) and is a **remote client** for `linkfyrd`: the phone talks to the PC over your own network, sends the exact same IPC envelopes the desktop app sends, and renders the same dashboard, tools, bridges, and alerts." },
      { type: "text", content: "No network engine runs on the phone by design. Mobile OSes forbid the raw sockets and OS commands the toolkit needs; the daemon is the engine, the phone is a first-class client. One contract, zero drift." },
      { type: "h3", content: "1. Start the daemon on your PC" },
      { type: "code", lang: "bash", content: "# Linux/macOS\nLINKFYR_WEB=0.0.0.0:58009 linkfyrd\n# Windows (PowerShell)\n$env:LINKFYR_WEB=\"0.0.0.0:58009\"; linkfyrd --service   # or run foreground" },
      { type: "text", content: "The daemon prints the token file path. Its content is the token the phone will use (`<config dir>/daemon.token`, 0600)." },
      { type: "text", content: "To get the full UI in the phone, copy the built frontend into the daemon's web directory once:" },
      { type: "code", lang: "bash", content: "pnpm build && cp -r apps/desktop/dist \"<config dir>/web-dist\"" },
      { type: "text", content: "Then `http://<pc-ip>:58009` already shows the dashboard in a phone browser. The Tauri mobile app wraps that same UI with a native shell and stores the token in the OS, so you do not need the copy step for the app itself; it talks to `/api/` directly." },
      { type: "h3", content: "2. Build the mobile app" },
      { type: "text", content: "Prerequisites: Rust stable, Node 22+, pnpm, and the platform toolchain for your target (Android Studio + NDK for Android, Xcode for iOS)." },
      { type: "code", lang: "bash", content: "pnpm install\ncd apps/mobile\n\n# One-time platform init (generates src-tauri/gen/...)\npnpm tauri android init\npnpm tauri ios init\n\n# Dev on a connected device/emulator\npnpm tauri android dev\npnpm tauri ios dev\n\n# Release builds\npnpm tauri android build   # Play Store artifacts (.aab injected per docs)\npnpm tauri ios build       # Archive for TestFlight/App Store" },
      { type: "text", content: "Verification in Docker (the same gate CI runs):" },
      { type: "code", lang: "bash", content: "powershell -File scripts/test/test-docker.ps1   # includes mobile typecheck + build" },
      { type: "h3", content: "3. First run on the phone" },
      { type: "list", items: ["Open the app; the setup screen asks for the PC address (`192.168.x.x:58009`) and the daemon token.", "It pings the daemon once and then renders the full UI.", "The token is stored only on this phone."] },
      { type: "h3", content: "Security posture" },
      { type: "list", items: ["The daemon binds loopback by default. Remote access is opt-in and LAN-scoped (`LINKFYR_WEB`); token auth (constant-time compare) is required on every request, and the phone sends it as a Bearer header.", "No cloud relay, no account, no telemetry. If you want access from outside your LAN, put the daemon behind your own VPN or reverse proxy; hosted relays are intentionally not part of v0.", "Threat model coverage: T1/T15 in `https://linkfyr.docs.potenfyr.in/docs/threat-model/`."] },
      { type: "h3", content: "Honest limits" },
      { type: "list", items: ["The phone cannot run tools that mutate the PC (DNS apply, bridges, enforcement) without the daemon being configured elevated there; capability states from the registry are shown as they really are.", "iOS background execution is restricted by the OS; the app works while foregrounded, which is the documented platform limit in `https://linkfyr.docs.potenfyr.in/docs/platform-support/`."] },
    ],
  },
  {
    slug: "platform-support",
    title: "Platform support",
    blurb: "Per-OS capability matrix that never fakes parity.",
    category: "Start here",
    blocks: [
      { type: "text", content: "Status: living document · Last updated: 2026-09-30" },
      { type: "text", content: "Rule: **never fake parity.** The UI renders this matrix at runtime (`capabilities()` API) and labels every feature: `available`, `partial`, `platform-policy` (blocked by the OS, not by us), `elevated` (needs an optional/privileged component), or `unavailable`." },
      { type: "h3", content: "Build targets" },
      { type: "table", headers: ["Platform", "Arch", "Tier", "Shipment"], rows: [["Windows 10/11", "x86_64", "P0", "MSI + NSIS + portable"], ["Windows 10/11", "ARM64", "P1", "MSI/NSIS (ARM64)"], ["macOS 13+", "aarch64", "P0", "DMG (universal2 where practical)"], ["macOS 13+", "x86_64", "P1", "via universal2"], ["Linux (glibc)", "x86_64", "P0", "AppImage, .deb, .rpm, tarball"], ["Linux (glibc)", "aarch64", "P1", ".deb, tarball, AppImage"], ["Android 10+", "arm64-v8a", "P2 (Phase 8)", "APK"], ["Android", "x86_64", "P3", "emulator builds"], ["iOS/iPadOS 16+", "arm64", "P2 (Phase 8)", "TestFlight/App Store (policy-limited)"], ["Headless Linux", "x86_64/aarch64", "P1", "`linkfyrd` + `linkfyr` tarballs, OCI image"], ["OpenWrt", "aarch64/mipsel", "P3 (Phase 9, research)", "ipk, not promised"]] },
      { type: "h3", content: "Capability matrix" },
      { type: "table", headers: ["Capability", "Windows", "macOS", "Linux", "Android", "iOS", "Headless"], rows: [["Interface discovery + counters", "✓", "✓", "✓", "partial¹", "partial¹", "✓"], ["Live throughput/health charts", "✓", "✓", "✓", "✓", "✓", "via CLI/API"], ["Per-app traffic visibility", "✓ (ETW/WFP)", "partial²", "✓ (uid/cgroup)", "partial¹", "✗ policy", "partial³"], ["Per-app allow/block firewall", "✓ (WFP)", "partial² (NE, approval)", "✓ (nft)", "✓ (VpnService)", "✗ policy", "✓"], ["Ask-to-connect prompts", "✓", "✓ (NE)", "✓ (OpenSnitch-style daemon)", "partial", "✗ policy", "✓ (API event)"], ["Per-app bandwidth limits", "✓ (WFP+qWAVE)", "partial²", "✓ (tc/fq+cake)", "✓", "✗ policy", "✓"], ["Interface selection per app", "✓", "partial²", "✓ (fwmark+policy routing)", "partial", "✗ policy", "✓"], ["Multi-WAN failover (local)", "✓", "✓", "✓", "partial", "✗ policy", "✓"], ["Local load balancing (per-flow)", "✓", "✓", "✓", "partial", "✗ policy", "✓"], ["Fusion bonding (true multipath)", "✓ (tunnel)", "✓ (NE tunnel)", "✓ (TUN)", "✓ (VpnService)", "✓ (PacketTunnel)", "✓ (edge role)"], ["Redundancy / FEC", "✓", "✓", "✓", "✓", "✓", "✓"], ["Per-app VPN routing", "✓", "partial²", "✓", "partial", "✗ policy", "✓"], ["WireGuard integration", "✓", "✓", "✓", "✓", "✓", "✓"], ["Encrypted DNS (DoH/DoT/DoQ)", "✓", "✓", "✓", "✓", "partial", "✓"], ["DNS blocklists/filtering", "✓", "✓", "✓", "✓", "partial", "✓"], ["Network Time Machine", "✓", "✓", "✓", "partial", "partial", "via API"], ["Diagnose engine", "✓", "✓", "✓", "✓", "partial", "✓"], ["Wi-Fi signal analysis", "✓", "partial (CoreWLAN limits)", "partial (driver-dependent)", "partial", "✗ policy", "✗"], ["Sysproxy (system proxy)", "✓", "✓", "✓ (DE-dependent)", "✗", "✗", "✓"], ["Remote management (Phase 8)", "✓", "✓", "✓", "✓", "✓", "✓"]] },
      { type: "text", content: "¹ Android/iOS expose only the app's own VPN-tunnel traffic plus coarse system stats; per-other-app detail is OS-policy-blocked. UI says so. ² macOS per-app features need a Network Extension (system extension approval); supported but gated by user approval + signing/notarization. ³ Headless sees process table where uid→process mapping exists." },
      { type: "h3", content: "Legend / gating in UI" },
      { type: "list", items: ["`elevated`: feature requires the privileged service component; installer offers \"core (no elevation)\" and \"full\" installs.", "`platform-policy`: OS restriction; rendered with an explanation, never a grayed-out mystery.", "Optional components (e.g. kernel callout driver on Windows, NE system extension on macOS) are downloadable from within the app with clear scope; the core product must remain useful without them."] },
      { type: "h3", content: "Tier policy" },
      { type: "text", content: "P0 blocks releases. P1 should follow within one release cycle. P2/P3 are roadmap-locked (https://linkfyr.docs.potenfyr.in/docs/roadmap/) with architecture reserved now." },
    ],
  },
  {
    slug: "protocol",
    title: "Fusion protocol",
    blurb: "The multipath bonding protocol design.",
    category: "Design and background",
    blocks: [
      { type: "text", content: "Status: draft, protocol selection requires benchmark ADR before Phase 6." },
      { type: "h3", content: "Goal" },
      { type: "text", content: "Aggregate N access networks into one virtual interface with a single stable egress IP at an Edge node, with smooth path migration and optional redundancy, while exposing every scheduling decision to the user." },
      { type: "h3", content: "Candidates to benchmark (ADR-00X will record results)" },
      { type: "list", items: ["**QUIC multipath (draft / mc-QUIC implementations)**, mature crypto, congestion control, streams; multipath still settling.", "**MPTCP**, kernel support spotty off Linux; NAT/traversal issues.", "**Custom UDP transport**, full control (path tags, scheduling, FEC hooks), cost: we own congestion control + crypto (use established primitives only). Likely hybrid: QUIC per-path + our session layer (sequencing/reordering/scheduling) on top."] },
      { type: "h3", content: "Session model (transport-agnostic)" },
      { type: "code", lang: "text", content: "Client                                    Edge\n  │ N paths (Ethernet/Wi-Fi/5G…) │\n  │──────── path handshake ─────▶│ authenticate (device key + token)\n  │  each path: AEAD-encrypted   │ assign session id + egress\n  │──────── data packets ───────▶│ per-packet: (session, path_id, seq, flags)\n  │◀─── downlink distribution ───│ scheduler feedback (RTT/loss samples)" },
      { type: "list", items: ["Packet header (draft): version(1) · type(1) · session(4) · path(1) · seq(6) · length(2) · flags(1), authenticated via AEAD, replay window per path. Headers avoid smuggling; control frames separate stream.", "Edge responsibilities: authenticate, sequence per (session,flow), dedup by (path,seq), reorder within jitter window, optional redundant strip, forward via NAT, accounting, telemetry back-channel.", "Client scheduler (runs every tick): weight_i = f(RTT_i, loss_i, capacity_i, cost_i, battery_i); smoothed (EWMA) + hysteresis to avoid flapping; per-traffic-class overrides (gaming → lowest RTT; download → max capacity).", "Redundancy modes: off · critical-only (small protected flows) · adaptive (duplicate when loss_i > threshold and spare capacity) · full.", "Failover: path death detected via keepalive loss; in-flight packets re-emitted on survivors (seq space shared per flow) → no TCP resets, no IP change (Edge anchor). This is the differentiator vs local-only.", "Migration/reconnect: session resumption tokens; Edge holds state for grace period (default 30 s)."] },
      { type: "h3", content: "Security" },
      { type: "list", items: ["Only established primitives (TLS 1.3 / QUIC crypto or WireGuard-style Noise family), no custom ciphers/modes. Keys from device identity + Edge enrollment; stored in OS keychain.", "Edge sees flow metadata (5-tuple) by necessity; client can pin self- hosted Edge to eliminate hosted trust.", "Anti-abuse: tokens per device, rate-limited handshake, QUIC-style address validation before data."] },
      { type: "h3", content: "Open items" },
      { type: "text", content: "FEC codec choice (RLNC vs XOR-based interleaving) · congestion control per path (BBRv2-style vs Copa for interactive) · header compression · MTU/probing · IPv6 · benchmark harness (doc'd with ADR)." },
    ],
  },
  {
    slug: "releases",
    title: "Release engineering",
    blurb: "Pipeline and idempotent publishing behavior.",
    category: "Design and background",
    blocks: [
      { type: "h3", content: "Channels" },
      { type: "text", content: "`stable` · `beta` · `nightly` (dev builds from main, suffixed `-nightly.YYYYMMDD.sha`). Nightlies skip some packaging (no delta notes)." },
      { type: "h3", content: "Pipeline (GitHub Actions, `.github/workflows/`)" },
      { type: "list", items: ["`ci.yml`: every push/PR: rustfmt, clippy -D warnings, cargo test (workspace), cargo deny (advisories/licenses), tsc, eslint, frontend unit tests.", "`release.yml` — on tag `v*` (or manual channel dispatch): build matrix →", "windows-x64, windows-arm64 (P1): MSI, NSIS exe", "macos (universal2): DMG (signed/notarized when creds present)", "linux-x64: AppImage, deb, rpm, tarball", "linux-arm64 (P1): deb, tarball", "headless: `linkfyr-cli-<os>-<arch>.tar.gz` + OCI image (optional) then: checksums SHA256SUMS, SBOM (CycloneDX), changelog from conventional commits, upload to GitHub Release, sign update manifests (Tauri updater signatures) when keys configured, publish latest.json for the updater, update install scripts' version pins.", "**Idempotent publishing**: re-releasing the same tag does not fail or duplicate - the release job updates the existing release's builds (gh release upload --clobber replaces same-named assets) and merges the changelog section into the body (skipped when already present). Notes come from CHANGELOG.md's ## [<version>] section, falling back to [Unreleased]."] },
      { type: "h3", content: "Artifacts layout (GitHub Releases)" },
      { type: "code", lang: "text", content: "LinkFYR_<ver>_x64-setup.exe / .msi     (Windows)\nLinkFYR_<ver>_aarch64-setup.exe/.msi   (Windows ARM64)\nLinkFYR_<ver>_universal.dmg            (macOS)\nLinkFYR_<ver>_amd64.AppImage/.deb/.rpm (Linux)\nlinkfyr-cli_<ver>_windows_x64.zip      (headless/CLI)\nlinkfyr-cli_<ver>_linux_x64.tar.gz\nlatest.json                            (updater manifest, signed)\nSHA256SUMS, sbom.cdx.json, CHANGELOG.md" },
      { type: "h3", content: "Install scripts (defensive, in /scripts, served from repo/raw or CDN)" },
      { type: "list", items: ["detect OS/arch; allow version/channel pinning via env", "fetch over HTTPS only; verify SHA-256 against published checksums", "`--no-exec` style piping protection: refuse when stdin is a pipe without `--yes`; never `sudo` without printing exactly what runs", "install to user prefix by default (`~/.linkfyr/bin`); `--system` opt-in", "writes uninstall script + PATH guidance; `--uninstall` supported", "rollback: previous version kept at `<prefix>/previous`"] },
      { type: "h3", content: "Updater (Tauri 2)" },
      { type: "list", items: ["`tauri-plugin-updater` with Ed25519-signed `latest.json`", "channels via update URL param; user-selectable in Settings", "check → download → verify signature → apply on restart", "Windows/macOS/Linux parity; portable builds check-only (manual swap)"] },
      { type: "h3", content: "Package managers (prioritized, not checklist-driven)" },
      { type: "text", content: "P1: WinGet (manifest PR automation), Scoop bucket, Homebrew cask/formula (tap first), AUR (-git + -bin). P2: Chocolatey, Flatpak (needs permissions review), Snap (sandbox friction, evaluate). Later: distro repos, Docker Hub/GHCR for edge + headless." },
    ],
  },
  {
    slug: "roadmap",
    title: "Roadmap",
    blurb: "Every feature classified Now/Next/Later; nothing is ever dropped.",
    category: "Start here",
    blocks: [
      { type: "text", content: "Status: living document · Last updated: 2026-09-30" },
      { type: "text", content: "**Preservation rule:** no idea from the product specification is ever deleted. Every feature is classified: **Now** (this phase) · **Next** · **Later** · **Experimental** · **Platform-limited** · **Research**. Deferred features must keep their architectural hooks (crate/module reserved, data model compatible)." },
      { type: "h3", content: "Phase 0. Research & Architecture ✅ (this repo start)" },
      { type: "list", items: ["Competitor matrix (https://linkfyr.docs.potenfyr.in/docs/competitors/), living doc", "User-demand research w/ evidence strength (https://linkfyr.docs.potenfyr.in/docs/user-demand-research/)", "Capability matrix (https://linkfyr.docs.potenfyr.in/docs/platform-support/)", "ADRs: 0001 shell (https://linkfyr.docs.potenfyr.in/docs/adr/0001-application-shell/), more follow each major decision", "Threat model + security policy (https://linkfyr.docs.potenfyr.in/docs/threat-model/, https://linkfyr.docs.potenfyr.in/docs/security/)"] },
      { type: "h3", content: "Phase 1. Foundation ✅ shipping now" },
      { type: "text", content: "**Now:** Tauri 2 app shell (Win/macOS/Linux desktop) · design system · UI shell (dashboard, interfaces, apps, diagnostics, settings, command palette) · linkfyrd service skeleton · linkfyr-ipc typed API · interface discovery · live per-interface telemetry (1 Hz) · health engine v0 · SQLite telemetry store · config store w/ backups + safe mode · logging (bounded, redacted) · CI validate/test · release pipeline w/ artifacts · install.sh / install.ps1 (checksum-verified) · signed updater plumbing · CLI: status/interfaces/traffic." },
      { type: "text", content: "**Next (Phase 1.5):** privileged service hardening split (named-pipe ACLs, SO_PEERCRED), tray app, Windows ARM64 CI, macOS signing/notarization (when credentials exist), WinGet/Scoop manifests, AUR." },
      { type: "h3", content: "Phase 2. Monitoring deep-dive" },
      { type: "text", content: "**Now:** per-app/process traffic table · destinations (domain/IP/ASN) · sessions view · historical analytics (1s→1m→1h buckets) · Network Time Machine (event log + scrubber) · health engine v1 (multi-factor, shown). **Next:** per-app history rollups, ASN/country enrichment (offline db), geographic map (opt-in), protocol mix. **Platform-limited:** Android/iOS granularity. **Research:** eBPF flow tagging on Linux for lower overhead." },
      { type: "h3", content: "Phase 2.6. Tool registry, bridges, daemon (shipped)" },
      { type: "text", content: "**Shipped:** the tool **registry**, the single catalog powering capabilities, CLI and UI; 108 modules implemented for real today (DNS family incl. DoH + record lookups + resolver agreement, route scan, latency monitor/jitter burst/ICMP ping/gateway, IPv6 readiness, bufferbloat, speed test, TTFB/TLS, port scan, per-app connections, listening ports, MTU, Wi-Fi, TCP audit, route audit, ARP, proxy, hosts, flush, public IP opt-in, DNS apply) with the generic `optimize run <id> key=value` envelope; the catalog is fully implemented (108 modules); no placeholders and no planned backlog remain. **Network bridge manager**: tiered. Hyper-V `New-VMSwitch` + embedded teaming (closest to the removed Windows bridge), `New-NetNat` forwarding fallback (always labeled as NAT, never as L2), Linux `ip link` bridges, macOS `ifconfig` bridges; elevation-honest reports list exact commands when not elevated. **linkfyrd background service**: hosts the engine over an authenticated loopback transport (token 0600, constant-time compare, loopback-only peers) reusing the exact IPC envelope; Windows SCM service wrapper (`--service`, cross-compile-checked in CI/Docker), systemd unit, launchd plist; exam-safe operation (close the GUI, telemetry + bridges keep running). **Alert engine**: interface up/down and health-drop transitions with a 100-entry ring surfaced via `get_alerts`, CLI `linkfyr alerts` and `linkfyr watch`." },
      { type: "text", content: "**Next:** implement remaining registry slots in batches (connection history journal, DHCP renew/release, adapter reset, DNSSEC/DNS-leak, wake-on-LAN, per-app limits once enforcement lands), daemon transport hardening (named pipe DACL / UDS peer credentials), bridge member auto-detection UI." },
      { type: "h3", content: "Phase 2.5. Optimization Toolkit (shipped)" },
      { type: "text", content: "**Shipped:** DNS resolver benchmark (real UDP queries, cached + uncached-path scoring) + OS apply with captured-previous restore · multi-path route scan (IPv4 vs IPv6 happy-eyeballs penalty detection) · bufferbloat measurement with A+..F grading (latency under real load) · speed test (real transfers; Cloudflare-compatible endpoints or self-hosted) · path-MTU discovery via DF pings (VPN/PPPoE black-hole finder) · TCP stack audit (Linux sysctl/qdisc, Windows netsh, macOS sysctl) with exact fix commands · Wi-Fi environment scan + channel recommendation (netsh / nmcli / airport parsers) · routing table audit (multi-WAN, VPN 0/1+128/1 hijack detection) · DNS cache flush repair · honest capability detection (available / elevated / unavailable / platform-limited) rendered in UI and CLI. All free, all local, no mocks: every number is measured. **Next:** TCP fixes apply-with-confirm, Wi-Fi channel auto-monitoring, historical optimization score tracking, network bridge manager (Linux `ip link`/macOS `ifconfig bridge` real commands now that Windows removed its bridge UI; Windows path needs an ADR - Wintun-based L2 or documented-as-unsupported), background service (`linkfyrd`) so long-running optimizations and bridging survive GUI closure (exam-mode safe operation)." },
      { type: "h3", content: "Phase 3. Local traffic control" },
      { type: "text", content: "**Now:** allow/block/ask per app · per-app limits (down/up) · priorities · interface assignment per app · bandwidth guarantees (hierarchical HSFC model) · borrowing/burst · profiles (Gaming/Streaming/Travel/Work/ Download/Custom) · profile auto-activation triggers (SSID, app launch, time, charging, battery). **Next:** smart reservation solver, schedules, app groups. **Platform-limited:** per-app control on iOS (policy)." },
      { type: "h3", content: "Phase 4. Flow Rules + Composer + Automation" },
      { type: "text", content: "**Now:** rule AST (conditions: app/process/user/interface/SSID/domain/CIDR/ ASN/port/protocol/category/time/battery/charging/health metrics/profile; actions: allow/block/ask/throttle/guarantee/priority/reroute/interface pick/VPN/DNS/profile/notify/webhook/diagnostics) · IF/THEN/UNLESS · beginner visual editor + expert editor · automation engine w/ dry-run, logs, explain-why · Connection Composer (visual graph → rules lowering). **Next:** rule sharing/import, versioned rule history, simulator mode." },
      { type: "h3", content: "Phase 5. Multi-WAN (local)" },
      { type: "text", content: "**Now:** failover (ordered, health-gated) · weighted per-flow balancing · app/destination/protocol-based routing · latency/cost/reliability-aware selection · adaptive link scheduler v1 (documented weights) · connection modes (Fusion*/Smart/Failover/Redundant*/LowestLatency/Download/Gaming/ Streaming/Conferencing/CostSaver/BatterySaver/LocalMultiWAN/Custom). **Next:** scheduler explainability UI upgrades, per-mode benchmark suite. **Research:** BBR/fq integration per-mode on Linux." },
      { type: "h3", content: "Phase 6. Fusion (bonding) + Edge" },
      { type: "text", content: "**Now(→Later as infra lands):** Fusion tunnel protocol (https://linkfyr.docs.potenfyr.in/docs/protocol/) · adaptive per-path scheduler · reordering/dedup · reconnect with smooth failover · redundancy modes (off/critical/adaptive/full) · self-hosted Edge (docker run linkfyr/edge) · hosted Edge (region rollout follows real infrastructure, no fake regions) · traffic accounting/telemetry. **Research (ADR required before build):** multipath-QUIC vs MPTCP vs custom UDP; FEC codecs (RLNC/fountain) benchmarked; 0-RTT roaming; static addresses. **Explicit honesty rule:** load balancing ≠ single-flow bonding; UI explains the difference." },
      { type: "h3", content: "Phase 7. VPN / DNS / Privacy" },
      { type: "text", content: "**Now:** DNS engine (system/custom/DoH/DoT/DoQ, per-app/per-profile DNS, fallbacks, benchmarking, custom hosts, blocklists/allowlists, family filter categories) · multi-VPN routing (per-app/per-destination; WireGuard first, then OpenVPN/SOCKS5/HTTP proxies/platform VPNs) · kill switches · privacy center (local-only mode, retention, telemetry opt-out, encrypted config sync opt-in). **Next:** split-tunnel UX unify with Flow Rules, DNSSEC validation posture, leak tests as first-class diagnostics." },
      { type: "h3", content: "Phase 8. Remote & multi-device" },
      { type: "text", content: "**Shipped (v0):** authenticated remote management (phone → PC), the Tauri 2 mobile companion in `apps/mobile` (Android/iOS) is a remote client for `linkfyrd`: the same UI source as desktop, the same IPC envelopes over HTTP with token auth, and a setup gate on first run. The daemon also serves the built dashboard at `LINKFYR_WEB` for plain browser access. Build/run guide: `https://linkfyr.docs.potenfyr.in/docs/mobile/`." },
      { type: "text", content: "**Next:** selective encrypted config sync (secrets never plaintext) · multi-device support (shared profiles/rules via encrypted sync) · fleet management (policies, centralized diagnostics, telemetry with privacy controls, RBAC, deployment automation), all free, self-hostable coordination. **Platform-limited:** iOS background execution (documented in the capability matrix)." },
      { type: "h3", content: "Phase 9. Router / headless / embedded" },
      { type: "text", content: "**Later:** linkfyrd as system service (systemd units shipped) · OCI/gateway images · OpenWrt feasibility (memory budget study) · NAS packages · BSD evaluation. **Research:** MIPS memory ceilings, flash footprint." },
      { type: "h3", content: "Cross-cutting commitments (all phases)" },
      { type: "list", items: ["Explainability: every automatic action explains why + one-click undo.", "Accessibility: keyboard-first, screen reader, reduced motion, WCAG AA.", "Performance budgets (https://linkfyr.docs.potenfyr.in/docs/architecture/ §9) enforced in CI benchmarks.", "Beginner/Expert progressive disclosure everywhere; expert mode hides nothing, beginner mode drowns no one.", "Security: threat-model review per phase; fuzzing for parsers; SBOM in every release; dependency audit gate.", "**No monetization.** LinkFYR is fully free (Apache-2.0 with the Commons Clause condition: use and build on it freely, do not sell the software itself as a paid product). Every feature ships to everyone: self-hosted Edge, hosted-bonding client support, CLI/API, unlimited history. No tiers, no entitlement gates, no locked controls. If hosted Edge infrastructure is ever operated, it must be fundable without paywalling software capability (donations/community hosting or user-supplied servers only; never feature-gated local functionality)."] },
    ],
  },
  {
    slug: "security",
    title: "Security engineering",
    blurb: "IPC hardening, supply chain, signing, and secrets.",
    category: "Security",
    blocks: [
      { type: "text", content: "# LinkFYR Security Policy" },
      { type: "text", content: "Status: living document Â· Last updated: 2026-09-30" },
      { type: "h3", content: "Principles" },
      { type: "list", items: ["**Least privilege.** GUI/CLI unprivileged; only `linkfyrd` is elevated.", "**Small, authenticated IPC.** Versioned, schema-checked messages; no reflection; deny-by-default method allowlist per caller.", "**Memory safety.** Rust everywhere; `unsafe` requires a written justification comment + review; fuzz every parser.", "**No custom crypto.** Standard primitives only (e.g. via `ring`/`rustls` family); primitives chosen in ADR before Fusion lands.", "**Fail-safe defaults.** Security features declare fail-open or fail-closed per feature (see threat-model Â§policy); user-visible.", "**Recoverability.** Config backups, safe mode, watchdog; LinkFYR must never leave the host offline after a crash (auto-restore filters on service death; heartbeat + supervisor restore on Windows service / systemd `Restart=` + `ExecStartPost` verification)."] },
      { type: "h3", content: "Supply chain" },
      { type: "list", items: ["`cargo audit` / `cargo deny` (advisories + licenses) gate CI.", "`npm audit` gate; lockfiles committed; Dependabot/Renovate enabled.", "SBOM (CycloneDX) per release artifact; checksums (SHA-256) published; signing (Authenticode/macOS codesign+notarization, minisign for tarballs) when credentials exist; update manifests signed (Tauri updater minisign/Ed25519 signature required â€” updates without valid signatures are rejected).", "Release provenance: build logs + toolchain pinned (rust-toolchain.toml)."] },
      { type: "h3", content: "Runtime hardening" },
      { type: "list", items: ["IPC: named pipe with restrictive DACL (Windows) / UDS in user-run dir with 0600 (unix) + peer-credential check; single-instance token; monotonic request IDs; malformed frames â†’ disconnect, not parse-and-hope.", "Secrets (VPN privkeys, Edge tokens): OS keychain (Credential Manager / Keychain / libsecret); never in config JSON; never logged (redaction filter on log sink).", "Logs: bounded ring + rotating files; destination IPs/domains minimized by default; `Export Diagnostic Report` is explicit, previewable, with redaction toggles.", "Updates: TLS-only fetches, cert pinning where feasible, signature check before swap, rollback on failed health check."] },
      { type: "h3", content: "Reporting" },
      { type: "text", content: "See README (security.txt path planned with public infra). Vulnerabilities in scope: local privilege escalation via IPC/service, rule bypass by unprivileged processes, tunnel crypto, update compromise, telemetry leaks." },
    ],
  },
  {
    slug: "threat-model",
    title: "Threat model",
    blurb: "STRIDE-annotated model and fail-open/fail-closed policy.",
    category: "Security",
    blocks: [
      { type: "text", content: "Scope: `linkfyrd` (privileged), IPC channel, GUI/CLI clients, Fusion tunnel + Edge, updater, telemetry store." },
      { type: "h3", content: "Assets" },
      { type: "text", content: "A1 privilege of `linkfyrd`; A2 user's Internet availability; A3 traffic metadata (destinations, apps); A4 tunnel secrets/keys; A5 update channel; A6 config/rules; A7 hosted-Edge trust." },
      { type: "h3", content: "Trust boundaries" },
      { type: "text", content: "TB1 unprivileged app ↔ `linkfyrd` IPC · TB2 `linkfyrd` ↔ kernel filters · TB3 client ↔ Edge over WAN · TB4 app ↔ update servers · TB5 any local process ↔ telemetry store." },
      { type: "h3", content: "Threats & mitigations" },
      { type: "table", headers: ["#", "STRIDE", "Threat", "Mitigation"], rows: [["T1", "S/E", "Malware on host calls IPC to whitelist itself / disable rules", "Pipe DACL + UDS perms; caller allowlist (only installed UI/CLI); mutating sessions require a token created interactively; audit log of privileged mutations"], ["T2", "S/E", "Service hijack → persistent LPE", "Minimal attack surface: no scripting in service, no plugins in v1, `unsafe` audit, fuzzed parsers, ASLR/DEP defaults, service runs with limited privileges beyond network config"], ["T3", "D", "linkfyrd crash leaves filters applied → host offline", "Heartbeat + supervisor auto-restore (\"fail-open watchdog\"); filters carry owner tag + TTL re-assertion; on service death, platform cleaner removes owned objects (documented per feature)"], ["T4", "D", "Malicious config/rules brick connectivity", "Config schema validation, dry-run apply + auto-rollback, safe mode (boot w/ LinkFYR disabled), config backups (N-keep)"], ["T5", "I", "Local process reads browsing metadata from store", "Store files ACL'd to user; telemetry redaction at write time; retention limits"], ["T6", "I", "Logs leak destinations/secrets", "Redaction sinks; secret types implement zero-on-drop + no-Debug"], ["T7", "I/E", "Malicious/compromised Edge node", "Client-authenticated + encrypted tunnel (Edge sees only forwarding metadata it must have); self-hosted mode removes hosted trust entirely; hosted regions published w/ jurisdiction"], ["T8", "I", "MITM on tunnel setup", "Server auth pinned to Edge public keys (TOFU + optional pinning); no plaintext fallback"], ["T9", "T", "Update compromise (A5)", "Signed manifests (Ed25519), TLS-only, signature-before-swap, staged rollout, rollback"], ["T10", "R", "User cannot tell why traffic moved", "Explainability events are first-class, signed sequence, queryable (also aids incident forensics)"], ["T11", "D", "Rule evaluation DoS (huge rule sets)", "Rule budget limits, evaluation timeout, O(1) indexes on common predicates, benchmarks in CI"], ["T12", "S", "Malicious app spoofs another process identity to evade per-app rules", "Windows: PID→image re-resolution each evaluation + WFP kernel attribution where available; Linux: uid/cgroup matching (harder to spoof); residual risk documented"], ["T13", "S/E", "Optimization toolkit mutations (DNS apply, TCP sysctls) abused to redirect or break resolution", "Mutations are explicit user actions only (never automatic); previous values captured before every apply and restorable one click; loopback interfaces never targeted; commands run argument-vector style (no shell); outcomes honestly reported (applied / needs_elevation / failed); elevation checked with the OS, not assumed"], ["T14", "I", "Optimization scans reveal topology (DNS queries, TCP connects, Wi-Fi surroundings) to the machine's operator only", "All measurements stay local: no result ever leaves the process (local-only default); scan targets are user-specified; Wi-Fi scans are read-only OS queries"], ["T15", "S/E", "linkfyrd loopback transport abused by another local process", "v1: TCP on 127.0.0.1 only + per-user token (0600, constant-time compare); loopback peer enforced per connection. v2 (hardening): Windows named pipe with DACL + unix domain socket + SO_PEERCRED so unauthenticated local peers cannot even connect; mutating requests additionally gated (T1 rules)"]] },
      { type: "h3", content: "Fail-open / fail-closed policy per feature" },
      { type: "table", headers: ["Feature", "Default on service failure", "User-adjustable"], rows: [["Monitoring only", "nothing to fail (pure observer)", "—"], ["Per-app block rules", "fail-open (blocks released)", "no (safety)"], ["Kill switch", "**fail-closed** (traffic held) while armed; auto-disarm option", "yes"], ["Fusion tunnel", "fail-open to underlying route (no black hole)", "yes (hold-last vs release)"], ["DNS takeover", "fail-open to system DNS", "yes"], ["Update check", "fail-open (offline stays offline-safe)", "—"], ["Optimization toolkit: measurements (DNS bench, route scan, bloat, speedtest, MTU, Wi-Fi, audits)", "fail-open: pure observers, a failed tool reports honestly and changes nothing", "no mutation involved"], ["Optimization toolkit: mutations (DNS apply now; TCP sysctl/netsh apply later)", "fail-open: apply is one-shot, reversible from captured previous values; never runs on boot or unattended", "yes (user-triggered only)"]] },
      { type: "h3", content: "Open risks (tracked)" },
      { type: "list", items: ["Windows user-mode WFP attribution vs admin-run apps (T12), callout driver deferred; matrix documents the gap.", "Linux distros without nftables (legacy iptables hosts), detection + degraded mode; capability surfaced honestly.", "macOS NE approval friction, onboarding copy + reset tooling."] },
    ],
  },
  {
    slug: "user-demand-research",
    title: "User demand research",
    blurb: "Community demand turned into evidence-graded requirements.",
    category: "Design and background",
    blocks: [
      { type: "text", content: "Grading: ★ widespread (many independent sources/longevity) · ☆ recurring (several sources) · ˚ anecdotal (single threads). Sources searched: Reddit (r/HomeNetworking, r/vpn, r/pcgaming, r/Twitch, r/homelab, r/macapps, r/sysadmin), GitHub issues (OpenSnitch, Portmaster, simplewall, GlassWire forums, Speedify), Hacker News, vendor forums." },
      { type: "h3", content: "Recurring asks → LinkFYR requirements" },
      { type: "table", headers: ["Ask (representative query)", "Evidence", "Maps to"], rows: [["\"combine Wi-Fi and Ethernet for speed\" / \"bond multiple internet connections\"", "★", "Fusion (P6) + honest local multi-WAN (P5)"], ["\"use multiple network adapters at the same time per app\"", "★", "interface assignment per app (P3)"], ["\"NetLimiter alternative modern UI\" / \"GlassWire with limits\"", "★", "Phase 3 shaping + Phase 1 visuals"], ["\"Little Snitch for Windows\" / \"Portmaster Windows\"", "★", "app firewall (P3), ask-to-connect (P3)"], ["\"per-app VPN / different VPN per application\"", "★", "multi-VPN routing (P7)"], ["\"prioritize Discord over Steam while downloading\"", "★", "guarantees/priority/borrowing (P3)"], ["\"internet failover without disconnect\" (calls dropping)", "★", "failover + Fusion seamless switch (P5/P6)"], ["\"Speedify too expensive / want self-host\"", "☆", "self-hosted Edge (P6), fully free local core"], ["\"GlassWire on Linux\"", "★", "Linux P0"], ["\"ask-to-connect too noisy\"", "☆", "fatigue-resistant prompts, learning suggestions"], ["\"why is my internet slow\" tooling beyond speedtest", "☆", "Diagnose engine w/ evidence + actions"], ["\"block app from internet but allow LAN\"", "★", "firewall scopes (P3)"], ["\"track which app used how much data this month (mobile caps)\"", "★", "metered caps, budget alerts (P2/P3)"], ["\"OpenWrt multi-WAN easier\" (mwan3 pain)", "☆", "desktop UX now; router later (P9)"], ["\"bandwidth reservation per app\"", "☆", "smart reservation (P3)"], ["\"network history / who downloaded what at 3am\"", "★", "Network Time Machine (P2)"], ["\"DNS per app / blocklists built-in\"", "☆", "DNS engine (P7)"], ["\"monitor per-process on Linux like GlassWire\"", "☆", "per-app monitor Linux (P2)"], ["\"Starlink + 5G bonding for rural\"", "☆", "Fusion + scheduler (P6), high-value niche"], ["\"explain what an app is connecting to\"", "★", "drill-down monitor (P2)"]] },
      { type: "h3", content: "Anti-patterns to avoid (complaint-derived)" },
      { type: "list", items: ["Subscription-gating *local* features users already paid hardware for ★", "Opaque \"AI optimization\" with no explanation ☆", "Notification spam from security tools ☆", "Ignoring Linux/ARM64 ☆", "UI rewrites that reset user rules/configs ˚"] },
      { type: "h3", content: "Open questions for continued research" },
      { type: "list", items: ["Size of \"bonding without cloud\" demand vs hosted convenience.", "Willingness to pay for Teams/fleet features.", "Android as full client vs companion-only."] },
    ],
  },
  {
    slug: "ux",
    title: "UX and design system",
    blurb: "Motion dials, design tokens, and the accessibility standard.",
    category: "Design and background",
    blocks: [
      { type: "h3", content: "Feel" },
      { type: "text", content: "Premium 2026+ network control center: technical but humane. Dark-first (v1 targets network engineers/gamers at night), excellent light mode. Information-dense when the user wants it, calm by default." },
      { type: "h3", content: "Design tokens (implemented in `packages/ui/tokens.css`)" },
      { type: "list", items: ["Type: Inter (UI) + JetBrains Mono (numbers/telemetry). Tabular numerals for all metrics. Scale: 12/13/15/17/20/24/30/38/48.", "Spacing: 4-base scale (4,8,12,16,24,32,48,64).", "Radii: 6/10/14/20; cards 14; pills 999.", "Elevation: 3 surfaces (base/raised/overlay) via layered translucent fills + 1px inner strokes; shadows only for true overlays.", "Color (dark): bg `#0B0E14`, surface `#11151F`, raised `#161B28`, stroke `#232A3B`, text `#E8ECF4`, muted `#93A0B4`. Semantic: accent `#5B8CFF` (LinkFYR blue), ok `#3DDC97`, warn `#FFB454`, danger `#FF5C7A`, info `#9B8CFF`. Interfaces get stable hues (Ethernet/Wi-Fi/cellular/virtual) from a categorical palette.", "Motion: 120ms/180ms/240ms; spring for spatial (expand/collapse, cards), ease-out for feedback; ALL animation gated by `prefers-reduced-motion` and a user animation-intensity setting (off/reduced/full).", "Charts: 2px strokes, area fills ≤12% alpha, live mode scrolls smoothly, hover readouts snap to samples, gap-safe (data gaps render as gaps)."] },
      { type: "h3", content: "Components (packages/ui primitives)" },
      { type: "text", content: "Button, IconButton, Card, Stat, Badge, Pill, Tabs, Segmented, Toggle, Slider, Select, TextField, SearchInput, Kbd, Tooltip, Popover, Dialog, Sheet, Toast, ProgressRing, Sparkline, LiveChart (area/line/stacked), BarMeter, HealthGauge (radial, factor breakdown), FlowDiagram (animated routing), Timeline (Time Machine), DataTable (virtualized), EmptyState, Skeleton, CommandPalette, CapabilityTag (available/partial/policy/ elevated), ExplainCard (\"why did LinkFYR do that\" + one-click undo)." },
      { type: "h3", content: "Layout" },
      { type: "text", content: "App shell: left rail (nav) + content + optional right inspector (expert mode). Command palette: Ctrl/Cmd+K. Views: Dashboard, Interfaces, Apps, Flow Rules, Composer, VPN, DNS, Diagnose, Time Machine, Tools, Settings." },
      { type: "text", content: "Dashboard default cards: Throughput (hero, combined ↓↑), Interfaces (contribution bars), Health (per-if), Top talkers, Recent decisions (explainability feed), Active profile, Alerts. Cards: hide/rearrange (drag), density toggle; multiple named dashboards later." },
      { type: "h3", content: "Accessibility" },
      { type: "text", content: "WCAG AA contrast on all token pairs; focus-visible rings; full keyboard nav + palette-first flows; charts have accessible summaries + table fallbacks; status never color-only (icon+text); reduced motion honored." },
      { type: "h3", content: "Performance" },
      { type: "text", content: "rAF-batched chart updates; virtualized lists everywhere; skeletons for" },
      { type: "note", tone: "info", content: "100ms loads; no layout-thrash animations (transform/opacity only)." },
    ],
  },
];

export function sectionBySlug(slug: string): DocSection | undefined {
  return DOC_SECTIONS.find((s) => s.slug === slug);
}
