[package]
name = "linkfyr-protocol"
description = "Fusion multipath bonding protocol: framing, reordering, path scheduling"
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
